name: CI - AI Release Notes

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd app
          npm install

      - name: Run basic tests
        run: |
          echo "Running sample test"
          node -e "console.log('✅ Node is working fine!')"

      - name: Generate AI release notes
        run: |
          echo "Generating release notes..."
          node app/scripts/generate_release_notes.js || echo "Fallback release note generated"

      - name: Show commit message
        run: echo "✅ CI workflow completed for commit: ${{ github.sha }}"
