name: CI - AI Release Notes

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd app
          npm install

      - name: Run basic test
        run: |
          echo "Running test script"
          node -e "console.log('✅ Node.js works fine!')"

      - name: Generate AI release notes
        run: |
          cd app
          if [ -f scripts/generate_release_notes.js ]; then
            echo "Running AI release note generator..."
            node scripts/generate_release_notes.js
          else
            echo "⚠️  Fallback: generate_release_notes.js not found, skipping"
          fi
          echo "-----------------------------"
          echo "✅ Release note generation step finished"
